### ISSUE TITLE
Include Etymology

### ISSUE THREAD

**Issue by ianfromdover** [GalileoBlues/Gallium#2]
How did this layout come to be named gallium?

Does it have any special meaning

**Comment by GalileoBlues** [comment]
Sorry for such a late reply, The naming convention for all of my layouts is an element from the periodic table that usually starts with a letter of a similar letter that has significance to the design philosophy. 

Gallium was named that because not only was i interested in getting the usage of the hands as close as possible to eachother but also the inner column usage of the indexes (the letters you have to reach for and contribute the lateral stretch bigrams). 

Typically a lot of optimised layouts place G and W on the bottom row and angle mod the layout so that something less frequent is in the 5th bottom row position, Instead Gallium has G in the middle inner column and i thought it significant enough to look for an element starting with the letter G. I found Gallium to sound nice, fit with the convention and it bears resemblance to my alias.
